### PR TITLE
Issue 7: Add more stub files for a more realistic site structure

### PR DESCRIPTION
**Pull request by darkwing**
Adding some stub files that many applications use.

### CODE REVIEW

**Comment by darkwing** [comment]
Let me know what you think of this.  I've _not_ added fonts to the repo, instead using Mozilla's CDN as requested by Tabzilla.

**Comment by marco-c** [comment]
Maybe we can add style/ and fonts/ directories as well?

We should add these files to the _template_ app though, not to the oghliner app.

**Comment by darkwing** [comment]
Updated!

**Comment by marco-c** [comment]
The file `favicon.ico` is duplicated (app/favicon.ico and app/images/favicon.ico)

**Comment by darkwing** [comment]
All updates made!

**Comment by marco-c** [comment]
For future reference, you can make issues automatically close with particular keywords in the commit message or the pull request:
https://help.github.com/articles/closing-issues-via-commit-messages/
https://github.com/blog/1506-closing-issues-via-pull-requests/

**Pull request merged**
