### PR TITLE
Don't use fs.exists/fs.existsSync

### LINKED ISSUE #66: Replace fs.exists/fs.existsSync with fs.access/fs.accessSync or fs.stat/fs.statSync
fs.exists and fs.existsSync are deprecated: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #66.

### CODE REVIEW

**Comment by brendandahl** [comment]
What about using a library or writing our own function? try/catch isn't very readable.

**Comment by marco-c** [comment]
We can use _fs.stat_ when try/catch makes things less readable.

**Comment by marco-c** [comment]
This should be ready now, I've removed the _try/catch_ and used the async fs.stat instead (which also allows us to have more information about the file). I've left _try/catch_ in one place because I think it was needed anyway and I added a comment to explain why.

**Comment by brendandahl** [comment]
needs a rebase, then it's good to go

**Comment by mykmelez** [comment]
@brendandahl Ready to merge now that it's rebased?

**Comment by brendandahl** [comment]
Yes, sorry ended up being out sick yesterday.

**Pull request merged**
