### PR TITLE
Support Node.js v4 and run tests on Travis with v0.12 and v4

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
Depends on #89.

**Comment by marco-c** [comment]
I'm going to close this PR for now, since we don't support Node.js 4 yet.

**Comment by mykmelez** [comment]
Now that https://github.com/pwmckenna/node-travis-encrypt/issues/17 has been merged, can this use the upstream module? Also, does this cause _after_success_ to run twice?

**Comment by marco-c** [comment]
> Now that pwmckenna/node-travis-encrypt#17 has been merged, can this use the upstream module?

We need to wait for a new version to be published, the contributor who merged my PR doesn't have privileges to publish to npm.
P.S.: It is https://github.com/pwmckenna/node-travis-encrypt/pull/16.

> Also, does this cause after_success to run twice?

Right, I forgot about this issue, I'll fix it.

**Comment by marco-c** [comment]
Filed #111 to use travis-encrypt again once the new version is published.

**Pull request merged**
