### PR TITLE
Don't tell the user that we're creating a temporary GitHub token for getting Travis token

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by mykmelez** [comment]
If we remove the _Creating_ message, then we also need to remove the _Deleting_ message.

**Comment by marco-c** [comment]
> If we remove the Creating message, then we also need to remove the Deleting message.

 Right, fixed in 3b4b4bb.

**Comment by mykmelez** [comment]
Hmm, strange, "completes basic flow" in testConfigure.js should fail with this change, but it doesn't. That test needs updating, but we should also figure out why it passes unexpectedly. The latter can be a followup.

The example in the README also needs updating.

**Comment by marco-c** [comment]
f7bd86a fixes the problem with the test.
4123061 removes the now unexpected messages from the test.
4114fe8 updates the README.

**Pull request merged**
